---
title: "R & Python"
author: "Imanol"
date: "10/2/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Reticulate

```{r}
library(reticulate) # Me habilita esta libreria en este fichero
use_python("/Users/Imano/anaconda3/python3.dll") # PAra que se instalen todas las librerias de anaconda
#py_install("nombre del paquete a instalar")
os <- import("os") # Importa una libreria de python y la guarda en una variable de R
os$listdir(".") # Para ver todas las carpetas y archivos que tiene
```

```{r}
source_python("LibreriaPythonPrueba.py") # para cargar una libreria que yo haya creado
add(3,4)
```

```{r}
np <- import("numpy", convert = FALSE) # Al poner convert = false le digo que no me haga una  
                                       # conversion de objetos Python a objetos R sino que vamos 
                                       # a trabajar con objetos nativos de python

x <- np$array(c(1:4))
sum <- x$cumsum()

print(sum) # Esto es un objeto python porque R no tiene listas, solo vectores

py_to_r(sum) # Para pasar de objeto python a objeto r

```

## Ayuda

```{r}
# Usar cualquiera de los dos
help("py_to_r")
py_help(os$chdir)
```

## Array

```{r}
a <- np_array(c(1:10), dtype = "float16")
a
```

```{r}
a <- np_array(c(1:10), order =  "C")
a
```

## Chunck directamente en python

```{python}
import numpy as np
import pandas as pd
```

## Para pasar datos a python desde R

```{r}
datos <- iris # iris es un datasheet
head(datos) # head nos da los primeros datos
datos_py <- r_to_py(datos)
```


```{python}
import numpy as np
import pandas as pd

r.datos_py.head() # Python empieza por 0 la tabla y R por 1
```

## Sparse Matrix
```{r}
library(Matrix)
N <- 6
set.seed(123) # Algo para el aleatorio
sparse_mat <- sparseMatrix(
  i = sample(N, N, replace = F), # filas, muestra aleatoria entre 1 y N, tamaño N, false para poner solo un dato
  j = sample(N, N, replace = F), # columnas, muestra aleatoria entre 1 y N, tamaño N, false para poner solo un dato
  x = runif(N), # El valor aleatorio entre 0 y N
  dims = c(N,N) # Dimension N filas N columnas
)
sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

```{python}
r.sparse_mat_py
```

```{r}
py_to_r(sparse_mat_py)
```

