---
title: "Tabla de frecuencias"
author: "Imanol"
date: "26/2/2021"
output: pdf_document
---
# Funciones para las Tablas de frecuencias

## Primera función
```{r}
TablaFrecs = function(x,k,A,p){ 
  L = min(x)-p/2+A*(0:k)
  x_cut = cut(x, breaks = L, right=FALSE)
  intervals = levels(x_cut)
  mc = (L[1]+L[2])/2+A*(0:(k-1))
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x),4) 
  Fr.cum.abs = cumsum(Fr.abs) 
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
  }
```


## Segunda función
```{r}
TablaFrecs.L = function(x,L,V){
  x_cut = cut(x, breaks=L, right=FALSE, include.lowest=V)
  intervals = levels(x_cut)
  mc = (L[1:(length(L)-1)]+L[2:length(L)])/2
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x),4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
  }
```

## Ejemplo

```{r}
petals = iris$Petal.Length
```

La tabla de frecuencias de la longitud de los pétalos *Iris* es:


```{r}
# k -> Numero de intervalos (Esta en cutre habria que usar scott o sturge...)
# A -> Amplitud
# p -> precision
TablaFrecs(petals, k = 6, A = 1, p = 0.1)

# L -> le damos los intervalos (Esta tambien a lo cutre)
# V -> FALSE para que no coja el limite de la derecha.
TablaFrecs.L(petals, L = 1:7, V = FALSE)
# Otra manera de poner L
TablaFrecs.L(petals, L = c(1,3,4,5,5.5,6,6.5,7), V = FALSE)
```

