---
title: "02 - Multivariantes"
author: "Imanol"
date: "19/2/2021"
output: pdf_document
---

# Datos multidimensionales

## Ejemplo con tres dimensiones

```{r}
ans = sample(c("Si","No"), size = 100, replace = TRUE)
sex = sample(c("H", "M"), size = 100, replace = TRUE)
place = sample(c("San Francisco", "Barcelona", "Valencia", "Cobija", "Asturias"), size = 100, replace = TRUE)
table(sex, ans, place)                             # Obtine una tabla bidimensional por cada ciudad
ftable(sex, ans, place)                            # Para hacerlo en una sola columna
ftable(sex, ans, place, col.vars = c("sex","ans")) # Para especificar que variable aparezca como fila y cual por columna (se ve mejor)
```

### Filtrar las tablas

```{r}
table(sex,ans,place)["M","Si","San Francisco"] 
table(sex,ans,place)[,"Si","Valencia"] 
table(sex,ans,place)[,"No",] 
table(sex,ans,place)["M",,"Cobija"] 
```

### Frecuencias relativas

```{r}
prop.table(table(sex,ans,place))                 # Frecuencias relativas globales
prop.table(table(sex,ans,place), margin = 3)     # Frecuencia relativa marginal por lugar
prop.table(table(sex,ans,place), margin = c(1,3)) # Frecuencia relativa marginal por sexo y lugar  

ftable(prop.table(table(sex, ans, place)))
```

