---
title: "04 - ejemplo final"
author: "Imanol"
date: "19/2/2021"
output: pdf_document
---

# Ejemplo final

## Juntar color de ojos y pelo sin distinguir por sexo

```{r}
ftable(HairEyeColor)
male <- HairEyeColor[, ,"Male"]
female <- HairEyeColor[, ,"Female"]
data <- as.table(male+female)
data
```

## Manipulación de datos
```{r}
dimnames(data) = list(
  Pelo = c("Negro", "Marron", "Pelirrojo", "Rubio"),
  Ojos = c("Marrones", "Azules", "Pardos", "Verdes")
)
data
```

## Diagrama de mosaico

```{r}
plot(data, col = c("lightblue"), main = "Diagrama de Mosaico")
```

## Datos númericos
```{r}
sum(data)
```
### Tablas de frecuencias absolutas y relativas de cada variable
```{r}
colSums(data) # Absoluta 
rowSums(data) # Absoluta
round(prop.table(colSums(data)),3) # Relativa
round(prop.table(rowSums(data)),3) # Relativa
```
```{r}
barplot(round(prop.table(colSums(data)),3), ylim = c(0, 0.4),
        col = c("burlywood4", "lightblue","orange3","lightgreen"), 
        main = "Frecuencias relativas\n de colores de ojos"
        )
barplot(round(prop.table(rowSums(data)),3), ylim = c(0, 0.5),
        col = c("black", "burlywood4","red","yellow"), 
        main = "Frecuencias relativas\n de colores de cabello"
        )
```
## Frecuencias relativas globales y marginales
```{r}
round(prop.table(data), 3)
round(prop.table(data, margin = 1), 3) # Porcentaje de color cabello en cada tipo de ojo
round(prop.table(data, margin = 2), 3) # Porcentaje de color ojo en cada tipo de pelo
```

```{r}
barplot(prop.table(data, margin = 1), beside = TRUE,
        legend.text = TRUE, ylim = c(0, 0.8),
        col = c("black", "burlywood4", "red", "gold"),
        main = "Feecuencias relativas del color de pelo\n para cada color de ojo."
        )

barplot(t(prop.table(data, margin = 2)), beside = TRUE,
        legend.text = TRUE, ylim = c(0, 0.6),
        col = c("burlywood4", "lightblue","orange3","lightgreen"),
        main = "Feecuencias relativas del color de ojos\n para cada color de pelo."
        )
# Hay que hacer la traspuesta porque sino sale girada al ser la 2 respecto de la 1
```

