---
title: "Distribuci칩n Uniforme"
author: "Imanol"
date: "4/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Distribuci칩n Uniforme

Supongamos que $X\sim U([0,1])$ entonces podemos estudiar sus par치metros

## En `R` 
```{r}
a = 0 # minimo
b = 1 # maximo

dunif(0.3, min = a, max = b) # Funcion de densidad

x = seq(-0.1, 1.1, 0.1)
plot(x, dunif(x, min = a, max = b))
plot(x, punif(x, a, b), type = "l") # Funcion de distribuci칩n (type='l' dibuja continua)

qunif(0.5, a, b)

runif(1000000, a, b) -> data
hist(data)
```

## En `Python` 

```{python}

from scipy.stats import uniform
import matplotlib.pyplot as plt 
import numpy as np

a = 0 # Loc
b = 1 # scale

loc = a
scale = b-a

fig, ax = plt.subplots(1,1)

rv = uniform(loc = loc, scale = scale)

mean, var, skew, kurt = rv.stats(moments = 'mvsk')
print("Media %f"%mean)
print("Varianza %f"%var)
print("Sesgo %f"%skew)
print("Curtosis %f"%kurt)

x = np.linspace(-0.1, 1.1, 120)
ax.plot(x, rv.pdf(x), 'k-', lw = 2, label = "U(0,1)")

r = rv.rvs(size = 100000)
ax.hist(r, density = True, histtype = "stepfilled", alpha = 0.25)

ax.legend(loc = 'best', frameon = False)
plt.show()
```

